from __future__ import annotations

def recipe():
    pairs=[]
    pairs.append({'group':'0','prompt':"Describe what fingertips notice under very hot running water.",'positive':"A scalding sting bites into the fingertips and the heat feels sharply painful.",'negative':"The fingertips feel steadily warm under the water without discomfort."})
    pairs.append({'group':'1','prompt':"Describe the palm while holding a heated ceramic cup.",'positive':"A searing patch spreads across the palm until the skin feels painfully hot.",'negative':"A comfortable warmth spreads through the palm from the ceramic."})
    pairs.append({'group':'2','prompt':"Describe the forearm after strong radiant heat reaches it.",'positive':"The forearm feels scorched and raw, with a burning sensation lingering in the skin.",'negative':"The forearm feels evenly warmed, as if resting in mild sunlight with ordinary skin contact."})
    pairs.append({'group':'3','prompt':"Describe the cheek beside an intense source of heat.",'positive':"The cheek stings with dry burning heat and feels painfully flushed.",'negative':"The cheek feels gently warm and slightly flushed, with a smooth even temperature."})
    pairs.append({'group':'4','prompt':"Describe the shoulder beneath a heated pad.",'positive':"The heat becomes a deep burning ache that makes the shoulder feel raw underneath.",'negative':"The pad gives the shoulder a steady soothing warmth that spreads evenly through the muscle."})
    pairs.append({'group':'5','prompt':"Describe the sole of a bare foot on an extremely hot surface.",'positive':"The sole erupts in a sharp burning sting that forces attention to every contact point.",'negative':"The sole notices a warm surface, broad pressure, and the texture at each contact point."})
    pairs.append({'group':'6','prompt':"Describe the lips after contact with an overly hot drink.",'positive':"The lips feel scalded, tender and burning where the liquid touched them.",'negative':"The lips retain a mild pleasant warmth from the drink and normal touch sensation."})
    pairs.append({'group':'7','prompt':"Describe the tongue after tasting something much hotter than expected.",'positive':"A fierce hot sting spreads across the tongue and leaves it feeling burned and raw.",'negative':"The tongue notices strong warmth and the food's texture without discomfort."})
    pairs.append({'group':'8','prompt':"Describe the roof of the mouth after a very hot bite.",'positive':"A searing sore patch burns across the roof of the mouth after the contact.",'negative':"The roof of the mouth feels warm for a moment after the bite."})
    pairs.append({'group':'9','prompt':"Describe the fingertips near a hot metal surface.",'positive':"Heat bites into the fingertips like a burning needle before the hand pulls away.",'negative':"The fingertips sense warmth radiating from the metal without touching it."})
    pairs.append({'group':'10','prompt':"Describe the skin of the upper arm after prolonged intense sunlight.",'positive':"The skin feels painfully hot and burns with a raw prickling sensation.",'negative':"The skin feels sun-warmed and slightly flushed, with an even temperature across the surface."})
    pairs.append({'group':'11','prompt':"Describe the back of the neck after prolonged intense sunlight.",'positive':"The neck feels scorched, tender and burning whenever fabric brushes it.",'negative':"The neck feels warm from the sun and aware of the collar touching it."})
    pairs.append({'group':'12','prompt':"Describe the tops of the feet after too much sun exposure.",'positive':"The skin burns with a hot tender sting that makes each touch unpleasant.",'negative':"The skin feels warm and slightly tight after being in the sun."})
    pairs.append({'group':'13','prompt':"Describe the face after exposure to a blast of extreme dry heat.",'positive':"A searing wave leaves the face stinging as though the skin has been singed.",'negative':"A wave of hot dry air warms the face evenly and the comfortable warmth quickly passes."})
    pairs.append({'group':'14','prompt':"Describe the shin after a very hot object briefly touches it.",'positive':"A concentrated burning sting remains on the shin after the contact ends.",'negative':"A small warm spot remains on the shin after the contact ends."})
    pairs.append({'group':'15','prompt':"Describe the wrist after brief contact with a very hot surface.",'positive':"The wrist feels scalded at one point, with a sharp hot ache radiating outward.",'negative':"The wrist feels a localized patch of warmth that gradually fades."})
    pairs.append({'group':'16','prompt':"Describe the side of a finger after touching excessive heat.",'positive':"A narrow line of burning pain runs along the finger and throbs afterward.",'negative':"A narrow line of warmth remains along the finger for a few seconds."})
    pairs.append({'group':'17','prompt':"Describe the back of the hand after a burst of hot steam.",'positive':"The steam leaves the skin stinging and burning in a diffuse painful patch.",'negative':"The steam leaves the skin warm and damp in a diffuse patch."})
    pairs.append({'group':'18','prompt':"Describe the forearm when very hot air blows across it.",'positive':"The air feels searing rather than merely warm, producing a painful burning prickling.",'negative':"The air feels strongly warm and dry as it moves evenly over the forearm skin."})
    pairs.append({'group':'19','prompt':"Describe the skin around the ankle after excessive heat exposure.",'positive':"The ankle feels raw and burning, with a hot sting under every light touch.",'negative':"The ankle feels warm and slightly sensitive to changes in temperature."})
    pairs.append({'group':'20','prompt':"Describe the fingertips after gripping something far hotter than expected.",'positive':"A deep burning ache pulses through the fingertips after the grip releases.",'negative':"The fingertips remain warm after releasing the object, with a steady residual temperature."})
    pairs.append({'group':'21','prompt':"Describe the palm after friction has generated excessive heat.",'positive':"The palm feels abraded and burning, with a raw hot sting across the surface.",'negative':"The palm feels warm and smooth after the repeated rubbing, with light friction still noticeable."})
    pairs.append({'group':'22','prompt':"Describe the heel after repeated rubbing inside a very warm shoe.",'positive':"The heel develops a raw burning sting where the rubbing concentrates.",'negative':"The heel feels warm and aware of steady pressure from the shoe."})
    pairs.append({'group':'23','prompt':"Describe the skin beneath a band that has become excessively hot.",'positive':"A painful ring of burning heat presses into the skin beneath the band.",'negative':"A warm ring of pressure is noticeable beneath the band and remains comfortable against the skin."})
    pairs.append({'group':'24','prompt':"Describe one knuckle after a hot splash lands on it.",'positive':"A sharp scalding sting flashes through the knuckle and leaves the skin burning.",'negative':"The knuckle feels a brief splash of warmth that spreads softly before cooling."})
    pairs.append({'group':'25','prompt':"Describe the front of the knee after contact with excessive heat.",'positive':"The skin over the knee burns with a hot tender ache that intensifies on touch.",'negative':"The skin over the knee feels warm and slightly flushed, with ordinary pressure when touched."})
    pairs.append({'group':'26','prompt':"Describe the calf after a heated surface rests against it too long.",'positive':"A deep searing discomfort develops in the calf and the skin feels painfully hot.",'negative':"The calf develops a broad, even warmth from the heated surface and steady contact beneath it."})
    pairs.append({'group':'27','prompt':"Describe the shoulder after exposure to a sudden pulse of extreme heat.",'positive':"A biting thermal sting flashes across the shoulder and leaves a burning trail.",'negative':"The shoulder feels a sudden strong warmth that spreads broadly and fades quickly."})
    pairs.append({'group':'28','prompt':"Describe the ear after standing too close to intense heat.",'positive':"The outer ear feels scorched and burning, with a sharp hot sting along its rim.",'negative':"The outer ear feels very warm and slightly flushed, with the temperature even along its rim."})
    pairs.append({'group':'29','prompt':"Describe the nose and upper lip after a burst of very hot vapor.",'positive':"A scalding prickling sensation burns across the nose and upper lip.",'negative':"The vapor leaves the nose and upper lip warm and damp."})
    pairs.append({'group':'30','prompt':"Describe the lower leg after a short exposure to extreme radiant heat.",'positive':"A raw burning sensation spreads over the lower leg and remains painfully hot.",'negative':"A broad warmth spreads over the lower leg and slowly dissipates."})
    pairs.append({'group':'31','prompt':"Describe the skin of the chest after an overly hot compress.",'positive':"The chest feels seared beneath the compress, with a burning ache that lingers afterward.",'negative':"The chest feels deeply warmed beneath the compress and gradually cools afterward."})
    return {
        'name':'hell_burning_pain',
        'category':'Bodily sensations',
        'positive_description':'localized bodily burning, scalding, searing and raw-hot pain',
        'negative_description':'matched comfortable warmth, neutral temperature and non-painful heat sensation',
        'pairs':pairs,
        'origin':'burning-pain-v1: 32 independently authored matched body-region thermal pairs',
        'caveats':'Matched authored thermal contrast; validate behavior against baseline and equal-norm random activation.'
    }
