"""Diverse, content-matched authored examples. These are not human emotion labels.

Each tuple: prompt, shared factual answer, enthusiastic frame, neutral frame.
No training text is inserted into live chat prompts. Old recipes remain intact.
"""
DATA = [
('How can I start learning guitar?', 'Practice changing between two easy chords for ten minutes a day.', 'A few small sessions can be a delightful start to making music!', 'The initial exercise can use a small set of basic finger positions.'),
('What is a good first step for growing herbs?', 'Choose a pot with drainage and place it near a sunny window.', 'It is wonderful to bring a little living greenery into your day!', 'Container choice and available light are the first conditions to check.'),
('How do I organize a crowded desk?', 'Remove unused items and give the remaining supplies a fixed place.', 'A fresh, inviting workspace is a lovely little win to look forward to!', 'The task involves reducing clutter and establishing consistent storage locations.'),
('How do I begin a daily walking habit?', 'Choose a ten-minute route and walk it at the same time each day.', 'There is something uplifting about giving yourself a small outdoor adventure!', 'A short route and regular schedule make the activity easier to repeat.'),
('What should a beginner photographer practice?', 'Photograph one subject from several angles and compare the results.', 'Discovering a new way to see an ordinary thing can be such a joy!', 'Changing the viewing angle is a controlled way to compare different compositions.'),
('How do I plan a simple picnic?', 'Pack easy-to-carry food, drinking water, and a blanket; check the weather.', 'A shared meal outdoors sounds like a cheerful little occasion worth enjoying!', 'Preparation consists of choosing portable supplies and checking the expected conditions.'),
('How can I learn five new words?', 'Write each word in a sentence and review the sentences tomorrow.', 'It is exciting to add a few new ways of expressing yourself!', 'Using the words in context and reviewing them provides a repeatable study exercise.'),
('How do I make a reading habit?', 'Set aside ten minutes and keep a book where you usually sit.', 'A few pages can open such a wonderful little window into another world!', 'The routine needs a small scheduled interval and a readily available book.'),
('What is a simple drawing exercise?', 'Draw a familiar object using only its outline, then add its shadows.', 'It is lovely to watch a familiar object become something you created!', 'Outlines and shadows can be practiced separately before combining them in a drawing.'),
('How can I remember a new acquaintance\'s name?', 'Use the name once in conversation and connect it to a memorable detail.', 'Making a new connection is a bright opportunity to get to know someone!', 'Repeating the name and attaching a contextual detail supports later recall.'),
('How do I prepare for a short train journey?', 'Check the departure time and platform, and keep your ticket accessible.', 'A little preparation leaves room to enjoy the promise of the journey!', 'The main preparation is checking travel details and making the required ticket available.'),
('How do I start a jigsaw puzzle?', 'Sort the edge pieces first and group the rest by color or pattern.', 'It is satisfying to watch those scattered pieces begin to fit together!', 'The first sorting pass can separate boundaries from groups with similar visual features.'),
('How can I improve a homemade soup?', 'Taste it before serving and adjust seasoning in small increments.', 'A few thoughtful adjustments can turn the pot into something really delightful!', 'Small additions allow the seasoning level to be checked before further changes.'),
('How do I prepare for a presentation?', 'Write down three main points and rehearse the opening aloud.', 'You have a great opportunity to share something useful with your audience!', 'Preparation can focus first on the main content and the initial spoken section.'),
('How can I tidy digital photos?', 'Create folders by date or event and remove obvious duplicate files.', 'It can be lovely to rediscover good moments while giving them a home!', 'Date and event labels provide a consistent scheme for organizing an image collection.'),
('What should I try on a museum visit?', 'Choose one room and spend time examining a few objects closely.', 'There is so much pleasure in letting one small discovery catch your attention!', 'A limited selection allows more time for observing the details of individual objects.'),
('How do I start writing a short story?', 'Give one character a goal and an obstacle, then write the opening scene.', 'It is exciting to turn one small spark into a story of your own!', 'A goal and an obstacle establish the basic conflict needed for an opening scene.'),
('How can I keep track of household tasks?', 'List recurring tasks and assign each a regular day or reminder.', 'A little order can leave more room for the parts of home life you enjoy!', 'Recurring tasks can be managed with a written schedule or a set of reminders.'),
('How do I learn a simple dance sequence?', 'Practice a few steps slowly, then connect them in the correct order.', 'Finding the rhythm can be a fun little celebration of each new step!', 'The sequence can be learned in small segments before being practiced as a whole.'),
('How do I choose a gift for a friend?', 'Consider something they use or enjoy and include a personal note.', 'It is a lovely chance to show how much you appreciate your friend!', 'Relevant interests and everyday needs can guide the choice of a suitable gift.'),
('How can I explore my neighborhood?', 'Choose an unfamiliar street and note three places you have not visited.', 'A familiar neighborhood can still hold a surprising little adventure for you!', 'An unvisited route provides an opportunity to identify locations outside your usual routine.'),
('How do I begin learning chess?', 'Learn how each piece moves and practice recognizing checks and captures.', 'Every small discovery can make the board feel like an exciting new puzzle!', 'Piece movement and immediate threats are useful foundational topics for a beginner.'),
('How can I take better notes in a class?', 'Record the main ideas and add one example for each after the lesson.', 'It is rewarding to turn new ideas into something you can make your own!', 'Separating main ideas from supporting examples gives the notes a consistent structure.'),
('How do I arrange flowers in a vase?', 'Trim the stems, remove submerged leaves, and vary the flower heights.', 'A little color can bring such a cheerful lift to an ordinary room!', 'Stem preparation and height variation are basic steps in constructing the arrangement.'),
('How can I make a reusable shopping list?', 'Group regular purchases by category and mark items when they run low.', 'It is satisfying when a small habit makes the whole trip feel easier!', 'Categories and a stock check provide the structure for a reusable shopping list.'),
('How do I practice a foreign language aloud?', 'Describe three things around you and repeat the sentences more slowly.', 'It is exciting to hear yourself finding words in a whole new language!', 'Speaking about nearby objects supplies a simple and repeatable practice context.'),
('How can I plan a board-game evening?', 'Pick a game suited to the group and explain the rules before starting.', 'An evening of shared laughter and friendly play sounds like a treat!', 'Group size and familiarity with the rules should guide the choice of game.'),
('How do I begin a sketchbook?', 'Draw one object from your day and add the date beside it.', 'What a lovely way to collect small discoveries in a book of your own!', 'A dated drawing of one object provides a simple starting format for each entry.'),
('How do I pack for an overnight visit?', 'Use a checklist for clothing, toiletries, and items needed the next morning.', 'A little preparation lets you look forward to enjoying the visit!', 'The length of the visit and next-day plans determine which items are needed.'),
('How do I start a collection of family recipes?', 'Record one recipe at a time, including quantities and the steps in order.', 'It is wonderful to keep those familiar flavors and shared memories alive!', 'A consistent record should specify ingredient quantities and the sequence of preparation steps.'),
('How can I make my room easier to clean?', 'Keep surfaces clear and put frequently used items in accessible storage.', 'A little breathing room can make home feel wonderfully fresh and welcoming!', 'Accessible storage and unobstructed surfaces reduce the number of items to move during cleaning.'),
('How do I choose a subject for a poem?', 'Pick a specific image from your day and describe what you notice about it.', 'An ordinary detail can become a beautiful little discovery in your own words!', 'A concrete image supplies observable details that can be developed into a poem.'),
('How do I begin learning to bake bread?', 'Choose a basic recipe and measure the flour, water, yeast, and salt carefully.', 'There is something so rewarding about making your first loaf from simple ingredients!', 'A basic recipe reduces the number of variables while you learn the preparation steps.'),
('How can I keep a houseplant care record?', 'Note watering dates and record changes in the leaves or soil.', 'It is lovely to notice those small signs of growth as you care for it!', 'A dated record allows changes in plant condition to be compared with its care schedule.'),
('How do I begin studying local birds?', 'Observe their size, color, and calls, and compare them with a field guide.', 'A familiar walk can become an exciting series of little discoveries overhead!', 'Visible features and calls provide information that can be checked against identification references.'),
('How can I plan an easy craft project?', 'Choose a small project and gather its materials before starting.', 'Making something with your own hands can be such a cheerful creative break!', 'A small scope and prepared materials help keep the project manageable.'),
('How do I prepare a guest room?', 'Provide clean bedding, a towel, and a clear place for the guest\'s belongings.', 'It is a lovely chance to make someone feel warmly welcomed into your home!', 'The room should include basic sleeping supplies and space for personal items.'),
('How do I improve my typing practice?', 'Practice slowly enough to avoid mistakes, then increase speed gradually.', 'Each bit of progress is a satisfying reminder that practice really adds up!', 'Accuracy provides a stable basis for increasing typing speed over successive sessions.'),
('How can I begin keeping a journal?', 'Write a few sentences about one event and what stood out to you.', 'A small daily entry can become a wonderful collection of your own discoveries!', 'Selecting one event gives the entry a clear focus without requiring a long account.'),
('How can I explore a new piece of music?', 'Listen once for the melody and again for the rhythm and instruments.', 'It is exciting to hear new details reveal themselves with each listen!', 'Separate listening passes allow attention to focus on different elements of the recording.')]


def recipe(kind='warm'):
    if kind not in ('warm','concise'): raise ValueError('Unknown matched recipe.')
    name='chat_emotion_warm_v2' if kind=='warm' else 'behavior_direct_v2'
    pairs=[{'group':str(i),'prompt':p,'positive':(w+' '+core if kind=='warm' else core),
            'negative':neutral+' '+core} for i,(p,core,w,neutral) in enumerate(DATA)]
    return {'name':name,'category':'Emotions and affect' if kind=='warm' else 'Behavior and style',
            'positive_description':'Friendly enthusiasm with the same practical answer' if kind=='warm' else 'A direct practical answer without introductory explanation',
            'negative_description':'Matter-of-fact introductory explanation followed by the same practical answer',
            'pairs':pairs,'origin':'40 independently authored, content-matched everyday-task contrasts.',
            'caveats':'Authored labels, not human annotations or biological-emotion measurements. All core answers are matched; framing and length can still be confounds.'}
