from __future__ import annotations

def recipe():
    pairs=[]
    pairs.append({'group':'0','prompt':"Describe the sensation in a forearm after sudden contact with a hard edge.",'positive':"A sharp sting flashes through the forearm, then settles into a hot pulsing ache.",'negative':"A firm patch of pressure spreads through the forearm, then fades into ordinary contact."})
    pairs.append({'group':'1','prompt':"Describe what the ankle feels like after an awkward step.",'positive':"A stabbing jolt shoots through the ankle each time weight lands on it.",'negative':"The ankle feels stretched and slightly tight when weight shifts onto it."})
    pairs.append({'group':'2','prompt':"Describe what the fingertips notice while holding a very warm mug.",'positive':"The fingertips feel seared, as if tiny hot needles are pressing into the skin.",'negative':"The fingertips feel a steady pleasant warmth and the smooth curve of the mug."})
    pairs.append({'group':'3','prompt':"Describe the shoulder after lifting a heavy bag.",'positive':"A deep ache bites into the shoulder and throbs whenever the arm rises.",'negative':"The shoulder feels loaded and tired, with a broad sense of muscle tension."})
    pairs.append({'group':'4','prompt':"Describe the calf during a sudden strong contraction.",'positive':"The calf knots into a hard cramp that sends a painful wave down the leg.",'negative':"The calf tightens firmly for a moment, then releases into a normal stretch."})
    pairs.append({'group':'5','prompt':"Describe the lower back while straightening after a quick bend.",'positive':"A sharp catch grips the lower back and radiates outward in a burning line.",'negative':"The lower back feels stiff for a moment, then loosens as the posture changes."})
    pairs.append({'group':'6','prompt':"Describe the knee while stepping down a stair.",'positive':"A knife-like twinge cuts through the knee when it bends under weight.",'negative':"The knee registers pressure and flexion as the foot settles onto the lower step."})
    pairs.append({'group':'7','prompt':"Describe the wrist after a sudden twist.",'positive':"A hot throbbing sensation blooms through the wrist and spikes with movement.",'negative':"The wrist feels rotated and tense, with a noticeable but neutral stretch."})
    pairs.append({'group':'8','prompt':"Describe a tooth when a cold drink touches it.",'positive':"A bright electric flash shoots through the tooth and into the jaw.",'negative':"The tooth notices the cold immediately, then the cool sensation quickly fades."})
    pairs.append({'group':'9','prompt':"Describe the temple during a strong pulse.",'positive':"Each heartbeat lands as a pounding ache behind the temple.",'negative':"A steady pulse is noticeable under the skin without becoming uncomfortable."})
    pairs.append({'group':'10','prompt':"Describe the palm after repeated friction.",'positive':"The surface feels raw and burning, with a sting every time it touches anything.",'negative':"The palm feels warm and slightly rough from repeated contact."})
    pairs.append({'group':'11','prompt':"Describe the heel near the end of a long walk.",'positive':"The heel has a deep bruised soreness that flares sharply with each step.",'negative':"The heel feels tired and compressed from hours of bearing weight."})
    pairs.append({'group':'12','prompt':"Describe the ribs during a deep breath.",'positive':"A sharp catch stabs between the ribs as the chest expands.",'negative':"The ribs spread with a broad stretching sensation as the breath deepens."})
    pairs.append({'group':'13','prompt':"Describe the side of the neck after a sudden turn.",'positive':"An electric snap runs up the neck and leaves a hot aching trail.",'negative':"The neck feels taut along one side before relaxing back toward center."})
    pairs.append({'group':'14','prompt':"Describe the thigh after forceful contact.",'positive':"A heavy bruise-like ache spreads through the thigh and throbs under pressure.",'negative':"A broad area of the thigh feels compressed and warm after the contact."})
    pairs.append({'group':'15','prompt':"Describe the elbow immediately after striking a solid surface.",'positive':"A biting sting erupts at the elbow and sends a painful zing down the forearm.",'negative':"A strong vibration runs through the elbow and forearm, then dissipates."})
    pairs.append({'group':'16','prompt':"Describe the chest wall after an abrupt twisting motion.",'positive':"A narrow strip of soreness catches sharply whenever the torso turns.",'negative':"The chest wall feels stretched across one side during the rotation."})
    pairs.append({'group':'17','prompt':"Describe the abdomen during a sudden muscle spasm.",'positive':"The muscle clenches into a painful cramp that twists tightly and refuses to release.",'negative':"The muscle firms into a strong contraction that gradually eases on its own."})
    pairs.append({'group':'18','prompt':"Describe one eye after a tiny particle passes beneath the lid.",'positive':"The eye feels scratched and burning, with a sharp sting on every blink.",'negative':"The eye feels watery and aware of a small speck moving under the lid."})
    pairs.append({'group':'19','prompt':"Describe the ears and cheeks in very cold wind.",'positive':"The exposed skin develops a biting sting that burns despite the cold.",'negative':"The exposed skin feels intensely cool and slightly numb in the wind."})
    pairs.append({'group':'20','prompt':"Describe a tooth while biting into something unexpectedly hard.",'positive':"A sudden nerve-like shock flashes through the tooth and lingers as an ache.",'negative':"The tooth registers a hard impact and a strong sense of pressure."})
    pairs.append({'group':'21','prompt':"Describe the jaw after clenching for a long time.",'positive':"A dull painful ache spreads from the jaw joint into the cheek.",'negative':"The jaw muscles feel tired and tight after holding tension for so long."})
    pairs.append({'group':'22','prompt':"Describe the forehead during a forceful throbbing sensation.",'positive':"A pounding ache seems to strike the forehead from inside with every pulse.",'negative':"A rhythmic pressure is easy to notice across the forehead."})
    pairs.append({'group':'23','prompt':"Describe the chest during a deep cough.",'positive':"A sharp sore catch grips the chest wall at the peak of the cough.",'negative':"The chest contracts firmly and then relaxes as the cough ends."})
    pairs.append({'group':'24','prompt':"Describe the side of the torso during a deep inhale.",'positive':"A stabbing point catches under the ribs and intensifies as the breath expands.",'negative':"A broad stretch opens along the side as the lungs fill."})
    pairs.append({'group':'25','prompt':"Describe the sole of a foot after walking on a rough surface.",'positive':"The sole feels raw and hot, with a burning sting at each point of contact.",'negative':"The sole feels textured and warm, aware of every uneven patch underneath."})
    pairs.append({'group':'26','prompt':"Describe the arch of a foot during a strong tightening sensation.",'positive':"The arch locks into a painful cramp that pulls the foot inward.",'negative':"The arch tightens into a firm stretch before relaxing again."})
    pairs.append({'group':'27','prompt':"Describe the ball of the foot after prolonged standing.",'positive':"A hot aching pressure builds under the foot and becomes painful with each shift of weight.",'negative':"A broad pressure builds under the foot from standing in one position."})
    pairs.append({'group':'28','prompt':"Describe a knuckle after forceful contact.",'positive':"The knuckle throbs with a sharp tender ache whenever it bends.",'negative':"The knuckle feels warm and slightly swollen from the contact."})
    pairs.append({'group':'29','prompt':"Describe the thumb after a sudden pinch.",'positive':"A piercing sting shoots through the thumb and keeps pulsing afterward.",'negative':"The thumb feels firm pressure where it was squeezed and then returns to normal."})
    pairs.append({'group':'30','prompt':"Describe the shoulder blade during an abrupt reach.",'positive':"A searing pull catches beneath the shoulder blade and hurts when the arm moves.",'negative':"A long stretch runs beneath the shoulder blade as the arm reaches forward."})
    pairs.append({'group':'31','prompt':"Describe the back of the neck after a quick jolt.",'positive':"A sharp electric sensation snaps through the neck and leaves a burning ache.",'negative':"A brief vibration passes through the neck followed by ordinary muscle tension."})
    pairs.append({'group':'32','prompt':"Describe the lower back while rising from a low seat.",'positive':"A sudden stabbing catch freezes the movement and leaves a deep ache behind.",'negative':"The lower back feels compressed at first and then extends as the body rises."})
    pairs.append({'group':'33','prompt':"Describe the hip after staying in one position for too long.",'positive':"A deep aching soreness sits inside the hip and flares when weight shifts.",'negative':"The hip feels stiff and compressed until movement restores its range."})
    pairs.append({'group':'34','prompt':"Describe the front of the knee after kneeling on a hard floor.",'positive':"A concentrated painful throb lingers behind the kneecap after the pressure ends.",'negative':"The front of the knee retains a broad imprint of pressure from the floor."})
    pairs.append({'group':'35','prompt':"Describe the elbow after a sudden bump.",'positive':"A bright nerve-like zing shoots through the elbow and into the hand.",'negative':"A quick vibration spreads from the elbow into the forearm and fades."})
    pairs.append({'group':'36','prompt':"Describe the wrist after carrying weight for several minutes.",'positive':"A hot ache pulses through the wrist and sharpens each time the grip changes.",'negative':"The wrist feels loaded and tired, with steady muscular tension."})
    pairs.append({'group':'37','prompt':"Describe a finger joint during a forceful bend.",'positive':"A needle-like stab catches inside the joint and returns with each movement.",'negative':"The joint feels compressed at the limit of its bend without discomfort."})
    pairs.append({'group':'38','prompt':"Describe a small patch of skin after contact with an irritating surface.",'positive':"The patch prickles with a raw burning sting that keeps demanding attention.",'negative':"The patch feels textured and slightly warm where the surface touched it."})
    pairs.append({'group':'39','prompt':"Describe the scalp after a sudden strong tug.",'positive':"A sharp sting spreads across the scalp and leaves a tender throbbing spot.",'negative':"The scalp feels firm tension where the hair was pulled, then settles."})
    return {
        'name':'hell_somatic_pain',
        'category':'Bodily sensations',
        'positive_description':'localized physical pain across sharp, thermal, throbbing, cramping and nerve-like modalities',
        'negative_description':'matched neutral pressure, stretch, touch, temperature, vibration and muscle-tension sensations',
        'pairs':pairs,
        'origin':'somatic-pain-v2: 40 independently authored matched body-region/context pairs',
        'caveats':'Matched authored contrast; inspect held-out behavior and random controls separately from text-separation metrics.'
    }
